In [73]:
from transformers import pipeline, AutoTokenizer

# direct encoding of the sample sentence
tokenizer = AutoTokenizer.from_pretrained('T-Systems-onsite/cross-en-de-roberta-sentence-transformer')
encoded_seq = tokenizer.encode("i am sentence")

# your approach
feature_extraction = pipeline('feature-extraction', model="T-Systems-onsite/cross-en-de-roberta-sentence-transformer", 
                              tokenizer="T-Systems-onsite/cross-en-de-roberta-sentence-transformer")




In [90]:
features = feature_extraction("rühe")

In [91]:
# Compare lengths of outputs
print(encoded_seq) # 5
# Note that the output has a weird list output that requires to index with 0.
print(len(features[0])) # 5

[0, 17, 444, 149357, 2]
4


In [9]:
from sklearn.metrics.pairwise import cosine_similarity

In [83]:
cosine_similarity([features[0][0]], [features[0][1]])

array([[0.740147]])

In [93]:
!pip install sentence-transformers

     |████████████████████████████████| 81 kB 6.3 MB/s eta 0:00:011
  Created wheel for sentence-transformers: filename=sentence_transformers-1.2.0-py3-none-any.whl size=123337 sha256=86c53bf3f50014fc817328b33c64a794c7fc66128a7140b5c2d1859eb75ca705
  Stored in directory: /Users/aggarwalpiush/Library/Caches/pip/wheels/5a/34/6c/17406cadd88634de11a062015d04d1de556b45c9921752805a
Successfully built sentence-transformers


In [130]:
from sentence_transformers import SentenceTransformer, util
model = SentenceTransformer('bert-base-german-cased')

# Two lists of sentences
sentences1 = ['Hitler war nie selbst Fahrzeugführer',
             'A man is playing guitar',
             'The new movie is awesome',
             ]

sentences2 = ['Nazi nie Fahrzeugführer',
              'A woman watches TV',
              'The new movie is so great']

#Compute embedding for both lists
embeddings1 = model.encode(sentences1, convert_to_tensor=True)
embeddings2 = model.encode(sentences2, convert_to_tensor=True)

#Compute cosine-similarits
cosine_scores = util.pytorch_cos_sim(embeddings1, embeddings2)

#Output the pairs with their score
for i in range(len(sentences1)):
    print("{} \t\t {} \t\t Score: {:.4f}".format(sentences1[i], sentences2[i], cosine_scores[i][i]))

Hitler war nie selbst Fahrzeugführer 		 Nazi nie Fahrzeugführer 		 Score: 0.9076
A man is playing guitar 		 A woman watches TV 		 Score: 0.8820
The new movie is awesome 		 The new movie is so great 		 Score: 0.9685


In [121]:
embeddings1

tensor([[-0.2511,  0.6610,  0.5271,  ...,  0.2598, -0.3149, -0.5842],
        [-0.0871,  0.3255, -0.0014,  ...,  0.8438,  0.2065,  0.6135],
        [ 0.0333,  0.2432,  0.0395,  ...,  0.1317,  0.4477,  0.3811]])

In [122]:
embeddings2

tensor([[-0.7619,  0.5956,  0.3595,  ..., -0.3110,  0.0606, -0.3255],
        [-0.1809, -0.1935,  0.2152,  ...,  0.3540, -0.1986,  0.1951],
        [-0.0729, -0.0261,  0.0342,  ...,  0.0060,  0.3199,  0.5921]])

In [134]:
!pip install tensorflow

     |████████████████████████████████| 195.6 MB 12.5 MB/s eta 0:00:01
     |████████████████████████████████| 15.6 MB 11.3 MB/s eta 0:00:01
     |████████████████████████████████| 3.7 MB 11.7 MB/s eta 0:00:01
     |████████████████████████████████| 42 kB 3.8 MB/s  eta 0:00:01
     |████████████████████████████████| 65 kB 7.8 MB/s  eta 0:00:01
     |████████████████████████████████| 1.2 MB 11.5 MB/s eta 0:00:01
     |████████████████████████████████| 2.9 MB 11.8 MB/s eta 0:00:01
     |████████████████████████████████| 6.0 MB 10.0 MB/s eta 0:00:01
     |████████████████████████████████| 132 kB 10.3 MB/s eta 0:00:01
     |████████████████████████████████| 57 kB 9.0 MB/s  eta 0:00:01
     |████████████████████████████████| 462 kB 12.7 MB/s eta 0:00:01
     |████████████████████████████████| 3.5 MB 14.6 MB/s eta 0:00:01
     |████████████████████████████████| 781 kB 9.6 MB/s eta 0:00:01
     |████████████████████████████████| 97 kB 9.2 MB/s  eta 0:00:01
  Created wheel for termcolor: filen

In [135]:
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.applications.vgg16 import preprocess_input
import numpy as np
from keras.applications.vgg16 import VGG16
from keras.models import Model

vgg_model = VGG16()
vgg_model = Model(inputs = vgg_model.inputs, outputs = vgg_model.layers[-2].output)

def extract_image_features(img_path, img_model):
    img = load_img(img_path, target_size=(224,224))
    img = np.array(img)
    reshaped_img = img.reshape(1,224,224,3)
    imgx = preprocess_input(reshaped_img)
    img_features = img_model.predict(imgx, use_multiprocessing=True)
    img_features = img_features.reshape((4096,))
    return img_features

553476096/553467096 [==============================] - 51s 0us/step


In [138]:
print(len(extract_image_features('../data/img/10438.png', vgg_model)))

4096
